//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Uploader
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_STG_DOC
    {
        public string ParentID { get; set; }
        public string ParentName { get; set; }
        public string DocID { get; set; }
        public string DocumentName { get; set; }
        public string CreationDate { get; set; }
        public string MimeType { get; set; }
        public string DocumentType { get; set; }
        public string ValidFrom { get; set; }
        public string ValidTo { get; set; }
        public string CustomerCode { get; set; }
        public string SupplierCode { get; set; }
        public string ProductCode { get; set; }
        public string ReferenceNo { get; set; }
        public string FormNo { get; set; }
        public string Type { get; set; }
        public string StaffName { get; set; }
        public string ProcessID { get; set; }
        public string OriginalProcessIS { get; set; }
        public string ParentProcessID { get; set; }
        public string ReferenceProcessID { get; set; }
        public string BatchNo { get; set; }
        public string BoxID { get; set; }
        public string Amount { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public string RetentionPeriod { get; set; }
        public string ReasonStatus { get; set; }
        public string Round { get; set; }
        public string SalesOrder { get; set; }
        public string DocumentDate { get; set; }
        public string Customer { get; set; }
        public string OrderType { get; set; }
        public string PONumber { get; set; }
        public string YourReference { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> UPLOADRETRY { get; set; }
        public Nullable<int> ISUPLOAD { get; set; }
        public string DOCURL { get; set; }
    }
}
