//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Uploader
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOADER
    {
        public string DOCID { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<bool> PROCESS_FLAG { get; set; }
        public Nullable<System.DateTime> PROCESSEDTIME { get; set; }
        public string RESULT { get; set; }
        public string UPLOADEDURL { get; set; }
        public string ERRORMESSAGE { get; set; }
        public Nullable<bool> ISUPDATEDSTAGING { get; set; }
        public Nullable<System.DateTime> STAGINGUPDATEDTIME { get; set; }
    }
}
